name: verify

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - id: get-version
        run: echo "::set-output name=CURRENT_VERSION::$(cat Makefile | head -n1|awk -F= '{print $2}')"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Run tests
        run: make all-test
        shell: bash